[phases.setup]
nixPkgs = ['jdk17']

[phases.build]
cmds = ['chmod +x gradlew', './gradlew clean bootJar --no-daemon']

[start]
cmd = 'java -Dspring.profiles.active=prod -Dserver.port=${PORT:-8080} -jar build/libs/Experiments-0.0.1-SNAPSHOT.jar'
