[phases.setup]
nixPkgs = ['jdk17']

[phases.build]
cmds = ['chmod +x gradlew', './gradlew clean bootJar --no-daemon']

[start]
cmd = 'java -jar build/libs/Experiments-0.0.1-SNAPSHOT.jar'

[variables]
SPRING_PROFILES_ACTIVE = 'prod'
